// stdout: a standard input stream, which is a source of input for the program (sends the information as data is being retreived out of the program (writeable stream))

// stdin: a standard output stream, which is a source of output for the program (listens for the user input (readable stream))

// stderr: a standard error stream used for error messages and diagnositcs issued by the program

// env: hosts all the environment variables set at the moment the process was started


// stdout: [Getter],
//   stdin: [Getter],
//   stderr: [Getter],
//   env: {
//     ACLOCAL_PATH: 'E:\\Program Files\\Git\\mingw64\\share\\aclocal;E:\\Program Files\\Git\\usr\\share\\aclocal',
//     ALLUSERSPROFILE: 'C:\\ProgramData',
//     APPDATA: 'C:\\Users\\Kai\\AppData\\Roaming',
//     APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: 'true',
//     CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_29268_SMAHUVDFONWBAVHO',
//     COLORTERM: 'truecolor',
//     COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
//     COMPUTERNAME: 'DESKTOP-KBEOHTG',
//     COMSPEC: 'C:\\Windows\\system32\\cmd.exe',
//     CONFIG_SITE: 'E:/Program Files/Git/etc/config.site',
//     'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
//     CommonProgramW6432: 'C:\\Program Files\\Common Files',
//     DISPLAY: 'needs-to-be-defined',
//     DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
//     EXEPATH: 'E:\\Program Files\\Git',
//     GIT_ASKPASS: 'c:\\Users\\Kai\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
//     HOME: 'C:\\Users\\Kai',
//     HOMEDRIVE: 'C:',
//     HOMEPATH: '\\Users\\Kai',
//     HOSTNAME: 'DESKTOP-KBEOHTG',
//     INFOPATH: 'E:\\Program Files\\Git\\usr\\local\\info;E:\\Program Files\\Git\\usr\\share\\info;E:\\Program Files\\Git\\usr\\info;E:\\Program Files\\Git\\share\\info',
//     LANG: 'en_US.UTF-8',
//     LOCALAPPDATA: 'C:\\Users\\Kai\\AppData\\Local',
//     LOGONSERVER: '\\\\DESKTOP-KBEOHTG',
//     MANPATH: 'E:\\Program Files\\Git\\mingw64\\local\\man;E:\\Program Files\\Git\\mingw64\\share\\man;E:\\Program Files\\Git\\usr\\local\\man;E:\\Program Files\\Git\\usr\\share\\man;E:\\Program Files\\Git\\usr\\man;E:\\Program Files\\Git\\share\\man',
//     MINGW_CHOST: 'x86_64-w64-mingw32',
//     MINGW_PACKAGE_PREFIX: 'mingw-w64-x86_64',
//     MINGW_PREFIX: 'E:/Program Files/Git/mingw64',
//     MSYSTEM: 'MINGW64',
//     MSYSTEM_CARCH: 'x86_64',
//     MSYSTEM_CHOST: 'x86_64-w64-mingw32',
//     MSYSTEM_PREFIX: 'E:/Program Files/Git/mingw64',
//     NUMBER_OF_PROCESSORS: '12',
//     OLDPWD: 'C:/Users/Kai/Desktop/devmountain/Interactive-Lectures/Week-12',
//     ORIGINAL_PATH: 'E:\\Program Files\\Git\\mingw64\\bin;E:\\Program Files\\Git\\usr\\bin;C:\\Users\\Kai\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Py.x;E:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\Users\\Kai\\AppData\\Local\\Programs\\Python\\Python38\\Scripts;C:\\Users\\Kai\\AppData\\Local\\Programs\\Python\\Python38;C:\\Users\\Kai\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Kai\\AppData\\Local\\atom\\bin;C:\\Users\\Kai\\AppData\\Roaming\\npm;C:\\Users\\Kai\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\heroku\\bin;C:\\Users\\Kai\\Desktop\\heroku\\bin',
//     ORIGINAL_TEMP: 'C:/Users/Kai/AppData/Local/Temp',
//     ORIGINAL_TMP: 'C:/Users/Kai/AppData/Local/Temp',
//     ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
//     OS: 'Windows_NT',
//     OneDrive: 'C:\\Users\\Kai\\OneDrive',
//     OneDriveConsumer: 'C:\\Users\\Kai\\OneDrive',
//     PATH: 'C:\\Users\\Kai\\bin;E:\\Program Files\\Git\\mingw64\\bin;E:\\Program Files\\Git\\usr\\local\\bin;E:\\Program Files\\Git\\usr\\bin;E:\\Program Files\\Git\\usr\\bin;E:\\Program Files\\Git\\mingw64\\bin;E:\\Program Files\\Git\\usr\\bin;C:\\Users\\Kai\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Py.x;E:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\Users\\Kai\\AppData\\Local\\Programs\\Python\\Python38\\Scripts;C:\\Users\\Kai\\AppData\\Local\\Programs\\Python\\Python38;C:\\Users\\Kai\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Kai\\AppData\\Local\\atom\\bin;C:\\Users\\Kai\\AppData\\Roaming\\npm;C:\\Users\\Kai\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\heroku\\bin;C:\\Users\\Kai\\Desktop\\heroku\\bin;E:\\Program Files\\Git\\usr\\bin\\vendor_perl;E:\\Program Files\\Git\\usr\\bin\\core_perl',
//     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
//     PKG_CONFIG_PATH: 'E:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;E:\\Program Files\\Git\\mingw64\\share\\pkgconfig',
//     PLINK_PROTOCOL: 'ssh',
//     PROCESSOR_ARCHITECTURE: 'AMD64',
//     PROCESSOR_IDENTIFIER: 'AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD',
//     PROCESSOR_LEVEL: '23',
//     PROCESSOR_REVISION: '7100',
//     PROGRAMFILES: 'C:\\Program Files',
//     PROMPT: '$P$G',
//     PS1: '\\[\\033]0;$TITLEPREFIX:$PWD\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ',
//     PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
//     PUBLIC: 'C:\\Users\\Public',
//     PWD: 'C:/Users/Kai/Desktop/devmountain/Afternoon-Projects/Week-12/web-node-drills-1',
//     ProgramData: 'C:\\ProgramData',
//     'ProgramFiles(x86)': 'C:\\Program Files (x86)',
//     ProgramW6432: 'C:\\Program Files',
//     SESSIONNAME: 'Console',
//     SHELL: 'E:\\Program Files\\Git\\usr\\bin\\bash.exe',
//     SHLVL: '3',
//     SSH_ASKPASS: 'E:/Program Files/Git/mingw64/bin/git-askpass.exe',
//     SYSTEMDRIVE: 'C:',
//     SYSTEMROOT: 'C:\\Windows',
//     TEMP: 'C:\\Users\\Kai\\AppData\\Local\\Temp',
//     TERM: 'xterm-256color',
//     TERM_PROGRAM: 'vscode',
//     TERM_PROGRAM_VERSION: '1.67.2',
//     TMP: 'C:\\Users\\Kai\\AppData\\Local\\Temp',
//     TMPDIR: 'C:\\Users\\Kai\\AppData\\Local\\Temp',
//     USERDOMAIN: 'DESKTOP-KBEOHTG',
//     USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-KBEOHTG',
//     USERNAME: 'Kai',
//     USERPROFILE: 'C:\\Users\\Kai',
//     VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
//     VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\Kai\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
//     VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\Kai\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
//     VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-392117865b-sock',
//     WINDIR: 'C:\\Windows',
//     _: 'C:/Program Files/nodejs/node'
//   }